# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\program\pyqt_fluent_test\examples\gallery\app\view\DetailFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Any
from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import BodyLabel, HorizontalFlipView, LargeTitleLabel

class Ui_DetailFrame(object):
    def setupUi(self, DetailFrame):
        DetailFrame.setObjectName("DetailFrame")
        #DetailFrame.resize(569, 427)
        self.gridLayout = QtWidgets.QGridLayout(DetailFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.Label2 = BodyLabel(DetailFrame)
        self.Label2.setObjectName("Label2")
        self.gridLayout.addWidget(self.Label2, 2, 2, 1, 1)
        self.Labe1l = BodyLabel(DetailFrame)
        self.Labe1l.setObjectName("Labe1l")
        self.gridLayout.addWidget(self.Labe1l, 2, 0, 1, 1)
        self.ScoreLabel = BodyLabel(DetailFrame)
        self.ScoreLabel.setObjectName("ScoreLabel")
        self.gridLayout.addWidget(self.ScoreLabel, 2, 3, 1, 1)
        self.HorizontalFlipView = HorizontalFlipView(DetailFrame)
        self.HorizontalFlipView.setMaximumSize(QtCore.QSize(1600, 900))
        self.HorizontalFlipView.setObjectName("HorizontalFlipView")
        self.gridLayout.addWidget(self.HorizontalFlipView, 0, 0, 1, 4)
        self.CompanyLabel = BodyLabel(DetailFrame)
        self.CompanyLabel.setText("")
        self.CompanyLabel.setProperty("strikeOut", False)
        self.CompanyLabel.setObjectName("CompanyLabel")
        self.gridLayout.addWidget(self.CompanyLabel, 2, 1, 1, 1)
        self.TitleLabel = LargeTitleLabel(DetailFrame)
        self.TitleLabel.setOpenExternalLinks(False)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 1, 0, 1, 2)
        self.gridLayout.setSizeConstraint(QtWidgets.QGridLayout.SetMaximumSize)

        self.retranslateUi(DetailFrame)
        QtCore.QMetaObject.connectSlotsByName(DetailFrame)

    def retranslateUi(self, DetailFrame):
        _translate = QtCore.QCoreApplication.translate
        DetailFrame.setWindowTitle(_translate("DetailFrame", "详情页"))
        self.Label2.setText(_translate("DetailFrame", "评分"))
        self.Labe1l.setText(_translate("DetailFrame", "厂商"))
        self.ScoreLabel.setText(_translate("DetailFrame", "0"))
        self.TitleLabel.setText(_translate("DetailFrame", "游戏名"))

class detailFrame(Ui_DetailFrame, QtWidgets.QFrame):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        self.setupUi(self)
